apiVersion: v2
appVersion: '1.0'
description: A Helm chart for labs-zc-hmcts App
name: labs-zc-hmcts
home: https://github.com/hmcts/labs-zc-hmcts
version: 0.0.2
dependencies:
  - name: nodejs
    version: 2.4.3
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
